---
title: "Untitled"
author: "Jiachen Feng"
date: "2021/2/10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(readxl)
library(tidyverse)
library(ggplot2)
library(stringr)
library(devtools)
pacman::p_load(tidyverse,
               gganimate,
               data.table,
               transformr)
```

```{r}
top40 <- read_excel("E:/Boston University/MA676/consulting1/simu/Mini case studies top 40 edit.xlsx", 
                    sheet = "Sheet1")
df <- list.files(path = "tabfolder", pattern = "*.tab", full.names = TRUE) %>% 
  map_dfr(fread, header = TRUE, .id = "year") %>% mutate(year = as.integer(year) + 2005)

top40 %>% inner_join(df,by=c("Country" = "country"))
df <- top40 %>% left_join(df, by = c("Country" = "country"))

df$yn <- substr(df$`Schengen Visa waiver Y/N (date)`,1,1)
df_sch <- filter(df,yn=='Y')

df_sch$schyear <- substr(df_sch$`Schengen Visa waiver Y/N (date)`,4,7) %>% 
  as.numeric() 

df_sch <- filter(df_sch,schyear>=2006) %>% 
  select(,c(1,10,11,12,14))
colnames(df_sch)[1] <- "country"

#unique(df_sch$schyear)

sch_09 <- filter(df_sch,schyear==2009)
sch_10 <- filter(df_sch,schyear==2010)
sch_11 <- filter(df_sch,schyear==2011)
sch_13 <- filter(df_sch,schyear==2013)
sch_14 <- filter(df_sch,schyear==2014)
sch_15 <- filter(df_sch,schyear==2015)
sch_17 <- filter(df_sch,schyear==2017)

```

```{r}

  
ani09 <- na.omit(sch_09) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_09$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_09$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)

ani10 <- na.omit(sch_10) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_10$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_10$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)

ani11 <- na.omit(sch_11) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_11$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_11$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)

ani13 <- na.omit(sch_13) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_13$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_13$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)

ani14 <- na.omit(sch_14) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_14$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_14$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)

ani15 <- na.omit(sch_15) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_15$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_15$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)

ani17 <- na.omit(sch_17) %>%
  ggplot(aes(x = year, y = access, color = country, group = country))+ 
  geom_point() +
  geom_line()+
  geom_vline(xintercept = sch_17$schyear,linetype="dotted",col='red',size=1.2)+
  annotate("text",x=sch_17$schyear,y=175,label="Schengen Visa-Waiver",col='red')+
  geom_text(aes(label = ranking, vjust = 1.1, hjust = -0.5, angle = 45))+
  labs(title = "Change of Access from 2006 (Rank of 2006: (0-10] )", subtitle = "{closest_state}", y = "Access", x = "Year", col = "Country") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=seq(2006, 2019, 1))+
  transition_states(states = country, state_length = 10)


animate(ani09, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen09.gif")

animate(ani10, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen10.gif")

animate(ani11, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen11.gif")

animate(ani13, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen13.gif")

animate(ani14, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen14.gif")

animate(ani15, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen15.gif")

animate(ani17, duration = 20, fps = 30, width = 2000, height = 2000, res = 300, renderer = gifski_renderer(loop = T))
anim_save("schengen17.gif")
  
```

